### ISSUE TITLE
Divide galleries

### ISSUE THREAD

**Issue by SimWhite** [mmistakes/hpstr-jekyll-theme#104]
Hello. Could you tell how do divide posts galleries?

I mean when I have some different posts with galleries on front page with the following code

Post 1:
```
{% capture images %}
  /images/posts/1.png
  /images/posts/2.png
  /images/posts/3.png
{% endcapture %}
{% include gallery images=images caption="gal1" cols=3 %}
```

Post 2:
```
{% capture images %}
  /images/posts/4.png
  /images/posts/5.png
  /images/posts/6.png
{% endcapture %}
{% include gallery images=images caption="gal2" cols=3 %}
```

And when I click on image it shows me all six images as one gallery, but it is the different posts, so I think it should be showed as different galleries.

P.S. Sorry for my English.

**Comment by mmistakes** [comment]
That's strange. Do you have a working example I can look at? I just tried using the code above and placing them in 2 different posts and it worked as intended for me. I got 2 galleries (1 in each post) each unique.

**Comment by mmistakes** [comment]
Reopen if you can provide a public repo so I can troubleshoot/test the issue.
