### ISSUE TITLE
SASS files are missing

### ISSUE THREAD

**Issue by nomanurrehman** [mmistakes/hpstr-jekyll-theme#107]
I am doing jekyll serve on my local machine but I keep getting this error.

Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    File to import not found or unreadable: base. Load path: /Volumes/Work/Blog/nomanurrehman.github.io/_sass on line 46

Lookin at line 46, it seems all the files included are missing from the `_sass` directory namely `base.scss`, `layout.scss`, and `syntax-highlighting.scss`.

// Import partials from `sass_dir` (defaults to `_sass`)
@import
        "base",
        "layout",
        "syntax-highlighting"
;

Am I missing something?

**Comment by mmistakes** [comment]
Maybe you're using an old version or have files from another theme? Is this from a new fork or did you add files to an existing Jekyll site.

The stylesheet the theme uses is [main.scss](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/assets/css/main.scss) and doesn't use any of the Sass partials you're getting errors for (base, layout, etc.). Leads me to believe you have some old files floating around in your repo from another theme.

**Comment by mmistakes** [comment]
Yup I was right. You have another main.scss file in /css/. No idea what that's for but it's looking for those Sass partials. My theme doesn't use that so remove it if you aren't using it for something.

**Comment by nomanurrehman** [comment]
Thanks for such a quick reply, really appreciate that.

And sorry for troubling you for no reason.
