### ISSUE TITLE
default thumbail for posts

### ISSUE THREAD

**Issue by vishaleckhart** [mmistakes/hpstr-jekyll-theme#114]
Is there a place to configure a default thumbnail?  
thank you

**Comment by mmistakes** [comment]
The theme doesn't use thumbnails... just large "hero" images at the top of posts/pages. You could easily modify the various layouts to show a default image whenever one isn't specified.

**Comment by vishaleckhart** [comment]
the avatar image shows up as a thumbnail sometimes, but not always, on facebook.  

---- On Thu, 27 Aug 2015 14:07:05 -0500 Michael Rose &lt;notifications@github.com&gt; wrote ---- 

The theme doesn't use thumbnails... just large "hero" images at the top of posts/pages. You could easily modify the various layouts to show a default image whenever one isn't specified.

**Comment by mmistakes** [comment]
That's related to Facebook's [open graph protocol](http://ogp.me/). You can specifically set what image you want Facebook to use by playing around with the `meta` data found in [`head.html`](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/_includes/head.html#L16). In the theme I set the large feature images for Twitter Cards, but didn't set an image for Facebook. It's easy enough to add if you want to use a default image, just look at the Twitter meta as an example of how.

In my experience even when you do set `og:image`, Facebook sometimes still has a mind of its own and grabs whatever image it feels is appropriate regardless.
