### ISSUE TITLE
Need to move index.html to blog/index.html

### ISSUE THREAD

**Issue by harshalisingh** [mmistakes/hpstr-jekyll-theme#117]
Hi, I want to add a custom Home Page (index.html) for my website and want to move the existing index.html to a folder named blog so that my blog url would be site-url/blog. What are the changes that I should be making?

**Comment by mmistakes** [comment]
Create a folder "blog" and move the index.html file there and you should be good to go.

**Comment by harshalisingh** [comment]
Thanks for replying. I did that however, index.html in blog folder is unable to display the posts. When I put it back in root location, the posts are visible.

**Comment by mmistakes** [comment]
Its probably getting confused with pagination code used for the homepage. You'll probably need to change `{% for post in paginator.posts %}` to `{% for post in site.posts %}` and then remove all the pagination link stuff in the div after the posts.

**Comment by mmistakes** [comment]
Also you have to play with [pagination settings](https://jekyllrb.com/docs/pagination/) in your `_config.yml`. Something like

```yaml
paginate_path: "/blog/page:num/"
```

In my experience getting `jekyll-paginate` to work anywhere except in the root of your site can be hard. Seeing how the plugin has been deprecated I don't have much hope things will improve anytime soon.

Closing as this isn't a theme issue.

**Comment by buddhikajay** [comment]
I know this is bit old, but this might help someone. Try this

```markdown
paginate: 5 # amount of posts to show
destination: _site/blog
```
