### ISSUE TITLE
Title disappear when reduce windows

### ISSUE THREAD

**Issue by algorys** [mmistakes/hpstr-jekyll-theme#119]
Hello,

I've installed your theme on my blog : http://algorys.github.io and on small screen or when I reduce my browser windows the title of post disappear.

I want to know if it is normal or not ?

Thanks

**Comment by mmistakes** [comment]
The title hiding is not normal. I just took a look at your repo and you made some changes to the CSS that's causing it to hide. Remove the `display: none;` on [this line](https://github.com/algorys/algorys.github.io/blob/master/_sass/_page.scss#L493) and it won't disappear on small screens anymore.

**Comment by algorys** [comment]
Oh. I don't remember made change on css...

Thanks.
