### ISSUE TITLE
Stack Exchange link not working?

### ISSUE THREAD

**Issue by siadevelopment** [mmistakes/hpstr-jekyll-theme#127]
Hello, I'm sorry I keep bugging you,

On my site under about I have Stack Exchange, however when put the site online and try to click the link, it loads "http://zoeyrae.com/312242/zoey-cluff" instead of stackexchange.com/312242/zoey-cluff. How can I fix this?

**Comment by mmistakes** [comment]
Use the full URL in your config and not just `312242/zoey-cluff/`. When in doubt check the navigation.html include to see what's what.
