### ISSUE TITLE
README.md Mentions Missing jekyll3 branch

### ISSUE THREAD

**Issue by eljobe** [mmistakes/hpstr-jekyll-theme#140]
Hello, I was reading your README.md and interested in using jekyll 3.0 on my blog. I saw this:

> Jekyll 3 Update: A version of HPSTR compatible with Jekyll 3 can be found in the jekyll3 branch. GitHub Pages is locked at version 2.4 so some keep that in mind if you're trying to use 3.0 features that aren't supported there yet.

But, that link is a 404. What's the status of jekyll 3.0 support for this theme?

**Comment by mmistakes** [comment]
That's something I forgot to remove. There is no `jekyll3` branch anymore since the theme [official supports Jekyll 3.0](https://github.com/mmistakes/hpstr-jekyll-theme/commit/35ff7b441f5e1e1a47903ee119273eb47a3b9ed0).
