### ISSUE TITLE
Missing url of blog in twitter

### ISSUE THREAD

**Issue by algorys** [mmistakes/hpstr-jekyll-theme#141]
Hello,

I use your theme for my [blog](http://algorys.github.io/) and I've a problem with the twitter link. When I click on twitter link, he only put end of url : 

For example if I click on icon twitter, he put `/tuto/fusion-inventory/` 

And not the full url, like this `http://algorys.github.io/tuto/fusion-inventory` in the tweet...

Is there a special configuration to do to avoid this problem or is it normal ?

My repo is here : https://github.com/algorys/algorys.github.io

Thanks for help.

**Comment by mmistakes** [comment]
You need to set `url: ` in your `_config.yml` file. Without it all links are relative and don't contain the domain, which is why the link shared to Twitter is missing it.

```yaml
# _config.yml
url: //algorys.github.io
```

**Comment by algorys** [comment]
Oops so simple... Thanks for help.
