### ISSUE TITLE
Feature Image

### ISSUE THREAD

**Issue by OdysLam** [mmistakes/hpstr-jekyll-theme#142]
Every time I use a feature image, it gets stretched out. I changed the dimensions multiple times, but it kept trying to cover all the height, every time I resized it to be smaller, it's just got granier and granier because of downscale.

Can't I use Images in their native dimensions as feature image without the stretch, just center them in the midle of feature-image box and have their native dimension.

New to web design as you can probably understand from my lingo.
Cheers!

**Comment by mmistakes** [comment]
Sounds like you're fighting against some of the CSS applied to the feature images. Basically what's going on is the `<img>` is being scaled to fill it's container, which in this case covers the entire width of the web page.

This is done so an image will automatically scale to fit no matter what the screen size is (mobile up to desktop). There's also some CSS on it to restrict the height so the overlaid titles don't get screwed up if the image is too short.

If you want to change any of these behaviors you'll need to edit the CSS which could be a challenge if you're new to web development. You'll want to start with the `.entry-image` class in [`_sass/page.scss`](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/_sass/_page.scss#L104) and start tinkering.

**Comment by OdysLam** [comment]
1)thanks for that swift response
2) I nearly got headache reading my previous message, apparently I had a stroke while writing it.

**Comment by OdysLam** [comment]
For anyone who might be interested, the fuckup option was the width %, changed to 10 and it works like a baby.
