### ISSUE TITLE
Refresh pages takes a long time

### ISSUE THREAD

**Issue by Yasashi** [mmistakes/hpstr-jekyll-theme#145]
Hi dear sir：

I’m now using your jekyll theme — HPSTR , thank you so much for providing this fantastic theme .

And now I just have a little question , each time I refresh the page , it will take a long time(during that the navigator on the left-top can't be clicked) , both the demo you provided (http://mmistakes.github.io/hpstr-jekyll-theme/) and my work (http://yasashi.github.io/) have the problem , do you know what’s the reason of it ,or could you fix it?

Thank you so much again！

**Comment by Yasashi** [comment]
I found that when it links to ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js in scripts.html , it takes a lot time.

**Comment by mmistakes** [comment]
If the externally hosted jQuery `ajax.googleapis.com` is giving you problems you can edit `scripts.html` to just use the jQuery in the theme instead. Change to this:

```html
<script src="{{ site.url }}/assets/js/vendor/jquery-1.9.1.min.js"></script>
<script src="{{ site.url }}/assets/js/scripts.min.js"></script>

{% if site.google_analytics %}
<!-- Asynchronous Google Analytics snippet -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{ site.google_analytics }}', 'auto');  
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');
</script>
{% endif %}

{% if page.comments != false %}{% include disqus_comments.html %}{% endif %}
```
