### ISSUE TITLE
Highlight code does not work for objective-c

### ISSUE THREAD

**Issue by Yasashi** [mmistakes/hpstr-jekyll-theme#146]
markdown appears:

![92a567be-8eed-44a8-b4ba-d231003b1fa6](https://cloud.githubusercontent.com/assets/12589575/14585920/d230c6fe-04b9-11e6-86c0-a75cb861204b.png)

highlighter appears:
![63554c7a-9925-4a2d-9dad-53615b2048cc](https://cloud.githubusercontent.com/assets/12589575/14585945/63d92d4e-04ba-11e6-8b43-7aadbc875470.png)

but not this:

```objectivec
NSString *evalString = [NSString stringWithFormat:@"jsFunction(%@)",args];
[self.commandDelegate evalJs:evalString];
```

**Comment by mmistakes** [comment]
Works for me using Jekyll's highlight tag like all of the [other examples](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/_posts/2013-08-16-code-highlighting-post.md) in the theme

```objc
{% highlight objc %}
NSString *evalString = [NSString stringWithFormat:@"jsFunction(%@)",args];
[self.commandDelegate evalJs:evalString];
{% endhighlight %}
```

![screen shot 2016-04-17 at 11 18 25 am](https://cloud.githubusercontent.com/assets/1376749/14588071/400d65d2-048e-11e6-90c7-ec9ba9d24594.png)

**Comment by Yasashi** [comment]
oops...I used "objectivec" it works on github but not jekyll, and I found change to "ruby" will be much better, thank u  all the way !
