### ISSUE TITLE
Navigation menu disappears on firefox android

### ISSUE THREAD

**Issue by piem** [mmistakes/hpstr-jekyll-theme#148]
hi!

The navigation menu seems to disappear on Firefox for Android 46.0.1. Moving `nav.dl-menuwrapper` after `div.entry-header` seems to help, but i'm not sure what else it breaks.

Thanks fro the great theme.

best, Paul

**Comment by mmistakes** [comment]
Maybe it's some sort `z-index` issue if moving it after the header makes it appear. Hard to say since I have no real way of debugging it.

**Comment by bricewge** [comment]
Setting `z-index: inherit` for `.dl-menu` fix this with Firefox 46.0.1 on Archlinux.

**Comment by mmistakes** [comment]
@piem I just pushed a [small CSS update](https://github.com/mmistakes/hpstr-jekyll-theme/commit/bd97490bd4b8c44ef059d315087b918a93143748) as per @bricewge's suggestion. Does this fix the issue for you?

**Comment by piem** [comment]
yes, it works perfectly now, thanks!
