### ISSUE TITLE
Running locally / running on Github - url independant setup

### ISSUE THREAD

**Issue by ddewaele** [mmistakes/hpstr-jekyll-theme#153]
First off.. thanks a lot for this great project ...  been searching for a long time for something like this.

A question on running this site locally (jekyll s) vs running on github.

Currently the theme forces you to specify a url
```
url:              //mmistakes.github.io/hpstr-jekyll-theme
```

When serving jekyll locally all links start pointing to the url as defined in the _config.yml, and not to localhost.

What would be a good way to be able to run it locally and on github pages with the same config?

**Comment by justinrummel** [comment]
What I do is create a separate _localhost.yml configuration that has one line in that file:
```url:              http://localhost:4000```

Then, when I want to test on my machine (with draft articles) I use the following commands:
```jekyll s -c _config.yml,_localhost.yml --drafts```

putting the _localhost.yml last overwrites the ```url:``` config line in _config.yml.

**Comment by mmistakes** [comment]
@justinrummel That's the way I suggest doing it as well. Or @ddewaele if using the `--config` flag isn't your thing you can just comment out the `url` like this when running Jekyll locally.

```
# url: https://your-domain.com
```

**Comment by ddewaele** [comment]
Thx !  Looking for something fail-safe so that I don't forget to un-comment it when I deploy to github pages. 

Too bad there is no out of the box variable that is exposed that contains current hostname. (like `site.github.url` but without the path).

But a localhost.yml with `--config` flag should do the trick.

**Comment by mmistakes** [comment]
I use rake tasks too to simple it, but yeah there's really no way around using multiple config files. At least until Jekyll exposes `url` similar to the `--baseurl ` flag with `jekyll serve`
