### ISSUE TITLE
Plugins on Github Pages / necessary to build locally and deploy manually ? 

### ISSUE THREAD

**Issue by ddewaele** [mmistakes/hpstr-jekyll-theme#154]
The Theme setup page mentions this : 

_If you’re using GitHub Pages to host your site be aware that plugins are disabled. So you’ll need to build your site locally and then manually deploy if you want to use this sweet plugin_

Had 2 questions on that stmt : 

- What plugins are being used that are not supported by Github pages ?
- Isn't the [demo-site](mmistakes.github.io/hpstr-jekyll-theme/) running from your `gh-pages` branch server by Github Pages without manually deploying it (meaning github is building your jekyll site) ?

**Comment by mmistakes** [comment]
The demo site is only using GitHub Pages whitelisted Jekyll plugins like `jekyll-paginate`. There's a few others like building a RSS feed, adding open graph tags for SEO benefits, emoji support, etc. Check the `github-pages` gem for the full list.

If you want to use Jekyll plugins not whitelisted you need to build your site locally and commit the compiled files found in `_site` to GitHub. In that case GH Pages isn't building your pages anymore and is just hosting your precompiled static assets.

If you Google around there are several methods for doing this.
