### ISSUE TITLE
Question on featured image behavior

### ISSUE THREAD

**Issue by latmarat** [mmistakes/hpstr-jekyll-theme#156]
Hello: 

First, thank you for this nice theme! I am trying to use a non-abstract featured image on my index page but it looks pretty bad  on mobile screens with the default behavior (squeezed along width). Could you please advise how to change the default behavior of the featured image to cropping for small screens?  Any other tip on how to improve the featured image representation for different screen sizes will be great too!

**Comment by mmistakes** [comment]
Check issue #142, I gave some background on the how the feature image is sized and can modified via CSS edits.
