### ISSUE TITLE
How to Set the feature image in xxxx/post and xxx/tags ?

### ISSUE THREAD

**Issue by Zhu-Zhi-Hao** [mmistakes/hpstr-jekyll-theme#162]
How to Set the feature image in xxxx/post and xxx/tags ? 
Just those two pages :
menu=>post=>all posts
menu=>posts=>all tags
How to Set the feature image in those two pages? 
Thinks...

**Comment by mmistakes** [comment]
You can set the [feature image](https://mmistakes.github.io/hpstr-jekyll-theme/theme-setup/#feature-images) for these 2 pages the same way you would for any other post or page. Add the relevant YAML Front Matter to either [`posts/index.html`](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/posts/index.html) or [`tags/index.html`](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/tags/index.html).

Example:

```yaml
image:
  feature: filename.jpg
  credit:
  creditlink:
```

**Comment by Zhu-Zhi-Hao** [comment]
Oh yes, Thinks very much ...
