### ISSUE TITLE
"Invalid Date: 'nil'" error when trying to serve locally with drafts

### ISSUE THREAD

**Issue by OutlierFinance** [mmistakes/hpstr-jekyll-theme#166]
I have noticed that when I am working with drafts locally and trying to test out my site with `bundle exec jekyll serve --drafts` I get the following error:

```
  Liquid Exception: Invalid Date: 'nil' is not a valid datetime. in sitemap.xml
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Date: 'nil' is not a valid datetime.
```

If I add an entry for `date` in the draft's front matter, the error goes away and jekyll can serve posts again, but I would rather not have to put a `date` field in drafts for fear of accidentally forgetting to remove this when I go to publish a post.

**Comment by mmistakes** [comment]
I don't control [**jekyll-sitemap**](https://github.com/jekyll/jekyll-sitemap) that generates `sitemap.xml` referenced in the error. I build Jekyll sites locally often with the `--drafts` flag and haven't encountered this problem before. Perhaps you're using an older version of the plugin. Have you tried `bundle update` then `bundle exec jekyll build --drafts`?

Only other suggestion I have is to check the issues on [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap) or file your own as it might be a bug with their plugin.

**Comment by OutlierFinance** [comment]
Thanks for the tips. I've done the `bundle update` already, so I'll check out the other repo for some more help.

**Comment by OutlierFinance** [comment]
I just did a bit more digging. I setup a bare-bones jekyll site with `jekyll new test` and installed the sitemap plugin there and I'm not experiencing any similar errors. I then tried a brand new clone of HPSTR, did `bundle update`, and tried serving with drafts and got the same `'nil'` error as before. I then tried disabling `jekyll-sitemap` in the `gems:` section of `_config.yml` and I am now getting a similar error on a different file.

```
  Liquid Exception: Invalid Date: 'nil' is not a valid datetime. in page2/index.html
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Date: 'nil' is not a valid datetime.
```

If I then also disable the `jekyll-paginate` plugin in `_config.yml`, then the `'nil'` errors go away. (Disabling jekyll-paginate and enabling jekyll-sitemap produces the error as well, so the issue is not the combination of the two plugins.)

All of the tests I've done that produce the error have been done on a fresh clone of HPSTR. Are you able to reproduce any of this on your system with a fresh clone of HPSTR? If not, perhaps there is a bigger issue with my machine that I need to sort out...

**Comment by mmistakes** [comment]
Now that you mention it I feel like I encountered something similar before when using `jekyll-paginate` gem. I don't often using pagination on my sites so it doesn't come up often. The fact that disabling that gem stops the error is highly suspect.

Maybe hit up jekyll-paginate's issues as well?

I've had other issues with that plugin so it wouldn't surprise me. Off hand I don't know why it would care about `page.date`. Makes more sense to me that jekyll-Sitemap would cause the error but I didn't write those plugins so really can't say either way.

I doubt `bundle exec jekyll build --drafts --verbose` will give you more info, but worth a try. It'll probably just show you the files it's processing and error on one of the drafts. Which you already know is an issue. But mabye there will be a clue on which plugin is really the culprit.

**Comment by mmistakes** [comment]
Also don't think this will matter because I don't think draft posts are "future dated." But maybe try removing `future: true` from _config.yml to disable future publishing.

**Comment by OutlierFinance** [comment]
Creating a fresh jekyll project and installing just pagination did not produce the error (though perhaps this is because I didn't add the pagination magic words to my site's main page).

Removing `future: true` solves the problem for me. From the docs it sounds like `future: true` will publish posts that have a date after today, which sounds undesirable anyway (if I've got a future date on the post, I would assume that the post won't be available until that date) so I'll just keep that line out of my config and call it solved. Should this be removed from the default config too?

**Comment by mmistakes** [comment]
I wouldn't expect adding that gem on its own to produce the error without `post.paginator` being invoked. So that explains why nothing bad happened when you added it.

As far as the future flag in _config.yml, that certainly doesn't need to be there. It's not something I make a habit of using so either it got in there from a pull request or was added a long time ago for some silly reason.

Either way no harm in ditching it.

**Comment by mmistakes** [comment]
If memory serves me it might have been added to get around time zone issues. There were/are cases where posts dated today wouldn't publish if the time zone isn't correctly set and it thinks it is date for tomorrow.

Setting it as true forced them through. There's so much nuance to Jekyll... pretty much any default I decide to roll with is going to break something for someone... Ugh!
