### ISSUE TITLE
Draft Posts not showing after autorestart

### ISSUE THREAD

**Issue by dtinblack** [mmistakes/hpstr-jekyll-theme#171]
I have added a _drafts folder into the hpstr folders to manage my draft posts.  

When I run "bundle exec jekyll serve --draft" to check and edit the format of a post the system autogenerates but loses the particular post.  If I edit a different draft post then the previous draft returns and the edited version disappears. 

I have checked the _site folder and when it autogenerates it fails to generate the draft folder for the post that has been edited. 

I have used the Developers Tools in Google to check the web site and there doesn't seem to be any errors ( apart from it not finding the draft post ). 

I am running jekyll 3.2.1. and using the localhost:4000 to develop my blog.

What should I check next ?

**Comment by mmistakes** [comment]
You'd be better off asking for Jekyll related [help on their forum](https://talk.jekyllrb.com/) for troubleshooting. This doesn't appear to be specific to the theme.

My guess you might need to enable the `future` flag in addition to `--draft`.

**Comment by mmistakes** [comment]
It could also be a bug with Jekyll. You're running an older version (current version is `3.4.0`) so I'd suggest updating and if you still have the problem with disappearing draft posts, [file an issue with Jekyll](https://github.com/jekyll/jekyll/issues) describing the steps to reproduce it so they can help.

**Comment by dtinblack** [comment]
I have upgraded to Jekyll 3.4.0 and it is working - thanks for suggestion.
