### ISSUE TITLE
No share button on FF Developer Edition- Windows 7

### ISSUE THREAD

**Issue by vtnlinh** [mmistakes/hpstr-jekyll-theme#177]
![image](https://cloud.githubusercontent.com/assets/16069263/26052581/2ad6eb74-3990-11e7-8825-59453581f7ad.png)

**Comment by mmistakes** [comment]
They're there. Verify that you don't have any adblockers installed. They will remove the share buttons. See related https://github.com/mmistakes/hpstr-jekyll-theme/issues/98

![screen shot 2017-05-15 at 6 56 34 am](https://cloud.githubusercontent.com/assets/1376749/26054746/bd601286-393b-11e7-954f-d4527024c583.png)
