### ISSUE TITLE
Date not show

### ISSUE THREAD

**Issue by vtrnnhlinh** [mmistakes/hpstr-jekyll-theme#180]
I changed date format into: `{{ page.date | date: "%d/%m/%Y" }}`, almost of pages show, but the About page isn't. 
![image](https://cloud.githubusercontent.com/assets/16069263/26754322/f82674f2-48a2-11e7-9866-266290d88fc0.png)
And this is my code shot:
![image](https://cloud.githubusercontent.com/assets/16069263/26754336/2a094b20-48a3-11e7-9b7d-5635e5e5928d.png)
And my code file:
[page.html](github.com/vtrnnhlinh/vtrnnhlinh.github.io/blob/master/_layouts/page.html)
And my About page:
[index.md](https://github.com/vtrnnhlinh/vtrnnhlinh.github.io/blob/master/gioi-thieu/index.md)
And my site address:
[My Blog](https://vtrnnhlinh.github.io/)
Thank you very much!

**Comment by mmistakes** [comment]
How are you assigning a date to your pages? Post's get it from the filename and will populate the `page.date` variable. Pages don't have a date and as you can see in the Liquid above it's looking for `page.modified`.

So you'll need to add the date to a page's YAML Front Matter like this if you want the date to show on "non-posts".

```yaml
modified: 2017-06-06T10:37:38-04:00
```
