### ISSUE TITLE
Unable to build to Github Pages

### ISSUE THREAD

**Issue by jss367** [mmistakes/hpstr-jekyll-theme#191]
I am unable to deploy this theme to Github Pages. I have followed your [setup instructions](https://mmistakes.github.io/hpstr-jekyll-theme/theme-setup/) by installing bundler, jekyll, etc., then forked and made a tiny edit to the _config.yml file. I am able to run the theme locally with `bundle exec jekyll serve`, but when I deploy to Github Pages the build fails and I get an error message in my email. Unfortunately, the error doesn't give me much information:

> The page build failed for the `master` branch with the following error:
> 
> Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/

I have set Github Pages to build from master. I also tried adding my URL to the _config.yml file but that had no effect. Just to test if I was doing something wrong, I did the same steps with your [minimal mistakes](https://github.com/mmistakes/minimal-mistakes) theme and the Github Page built with no problem. My [page](https://github.com/jss367/hpstr-jekyll-theme) is a direct fork of this one. Is there something else I should be doing?

**Comment by jss367** [comment]
It ended up being the additional keys in the front matter for posts with images. This part was fine:

image:
  feature: abstract-3.jpg

but I had to remove the credit and creditlink tags from the following posts:

_posts/2011-03-10-sample-post.md
_posts/2012-05-22-readability-post.md
_posts/2013-05-23-readability-feature-post.md
_posts/2013-08-16-code-highlighting-post.md

**Comment by barbourww** [comment]
Thanks for the resolution of this. Worked for me as well. Not sure how to get this change pushed to master - might just be easiest for @mmistakes to make the four small changes.

**Comment by barbourww** [comment]
The image credit and conditional statement to activate it is still in the layout for posts and pages (e.g., _layouts/post.html). I don't recall what the exact issue with the build failure was, but it should certainly be possible to fix those links or fix the keys in the front matter. I suspect (though without evidence from testing) that it has something to do with the sub-key for the credit (i.e., post.image.credit) and might be resolved by just declaring post.image-credit at the same level as post.image in the front matter.

**Comment by mmistakes** [comment]
The issue is when hosting with GitHub Pages they load the [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) plugin, which gets tripped up with the `image` object.

Changing the layout won't have any affect because jekyll-seo-tag doesn't like the post YAML Front Matter used for `image`. When it's defined as an object it expects a `path` key, which is why it's failing.

The fix is to add a `path` key that duplicates the value of `feature` (or `background` if you're using background patterns).

```yaml
image:
  feature: abstract-6.jpg
  path: abstract-6.jpg # duplicate value of feature
  credit: dargadgetz
  creditlink: http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/
```
