### ISSUE TITLE
About Menu Icon Disappears

### ISSUE THREAD

**Issue by IcyTesseract** [mmistakes/hpstr-jekyll-theme#37]
When you press the about menu icon (the one with three lines representing it by default) and then click out, the icon disappears and only reappears if you manage to hover over its invisible box.

Issue reproducible in Safari, but not Chrome

**Comment by rahul-rkt** [comment]
I have not faced this issue whie using Safari even once. It seems to work fine for me, but while in mobile, the menu does not close when you tap the screen outside, like it does on desktop if I click somewhere on the page outside the menu boundaries.

**Comment by IcyTesseract** [comment]
Closing because it has been working at least as of Safari 7.1.4 for me. Must have been something Safari related and not related to this project.
