### ISSUE TITLE
How to make the home page only shows article summaries?

### ISSUE THREAD

**Issue by ghost** [mmistakes/hpstr-jekyll-theme#47]
I just want my article show a part of it in the home page,what should I do?

**Comment by neelambar** [comment]
Hi,
is there any way to correctly display reading time (based on complete post content) on the index.html when using excerpt ?

Thanks.

**Comment by mmistakes** [comment]
@neelambar This was a bug, it was incorrectly displaying the reading time for all posts on the index pages regardless if you were using excerpts or not. It was calculating the read time for the index.html page and applying that to each post.

I just [pushed a fixed](https://github.com/mmistakes/hpstr-jekyll-theme/commit/f8a46160a15638d604ab1b138e8872e9c06effc9) to take care of it.

**Comment by neelambar** [comment]
Thank a lot. It is working now.
