### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by TaylanTatli** [mmistakes/hpstr-jekyll-theme#53]
Is it possible to add search on this theme like your other themes? Sorry for my English.

**Comment by christophekumor** [comment]
damm, just installed and customised this theme, and was looking to add search.. 
it seem to be a big work to add it .. 8-(
I dont linke So Simple theme, i prefer stay with HPSTR.. perhaps one day someone will add this feature.

thx you for you work ! Amazing work on jekkyl themes !!
