### ISSUE TITLE
tags in posts

### ISSUE THREAD

**Issue by baurigae** [mmistakes/hpstr-jekyll-theme#75]
Thank you very much for sharing the theme, I like it very much and like hacking on it. So being a novice to the Jekyll world I was wondering if it's possible to have post tags show up in individual posts, instead of only in the tag archive page?

**Comment by mmistakes** [comment]
You'll have to modify the layouts and style the post tag links to display how you like, but it's a pretty easy thing to hack up. I didn't add them to this theme, but if you look at my other one [So Simple](https://github.com/mmistakes/so-simple-theme) you can see how I did it.

Basically you add something like the following and it will output all of the tags assigned to the current post.

``` html
{% for tag in page.tags %}<a href="{{ site.url }}/tags/#{{ tag }}">{{ tag }}</a>{% unless forloop.last %},{% endunless %}{% endfor %}
```

**Comment by baurigae** [comment]
Thanks! The other theme looks great too.
