### ISSUE TITLE
new Octopress draft option

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/hpstr-jekyll-theme#78]
when performing a ```octopress new draft "title goes here"``` it does not respect the _octopress.yml file conditions for posts using the .md file extension.  However, if you copy/paste this into the _config.yml it performs as expected.  This just may be an Octopress issue not looking at the _octopress.yml file, but I would suggest to just copy/paste the contents into one file.

**Comment by mmistakes** [comment]
It could be an Octopress issue. I don't use it personally to know though. I just bundled it in the theme because it was a better alternative to some custom Rake tasks I had before.

**Comment by mmistakes** [comment]
Closing as this appears to be related to the Octopress gem and not the theme.
