### ISSUE TITLE
Remove Google Authorship

### ISSUE THREAD

**Issue by marpstar** [mmistakes/hpstr-jekyll-theme#79]
Google ended it's Authorship program in August 2014. Link to https://plus.google.com/authorship in `_config.yml` now redirects to https://support.google.com/webmasters/answer/6083347?hl=en, which states 

> Authorship markup is no longer supported in web search.

Line in `head.html` should be removed:

    {% if site.owner.google_plus %}<link rel="author" href="https://google.com/{{ site.owner.google_plus }}?rel=author">{% endif %}

Obviously low priority, but worth mentioning. Google offers alternatives, but maybe Open Graph and Twitter Cards are enough?

**Comment by mmistakes** [comment]
Good idea, this totally should come out.

- [ ] remove Google Authorship from `head.html` include
- [ ] remove mention of Google Authorship from `_config.yml`
- [ ] remove mentions of Google Authorship from **Theme Setup**
