### ISSUE TITLE
Previous button doesn't link to the first page

### ISSUE THREAD

**Issue by procedural** [mmistakes/hpstr-jekyll-theme#83]
I've just cloned the repo and run the website, if you click Next button to move on to page 2 and try to go back by hovering over Previous button you'll see it points to `http://localhost:4000/page2/` still, but it should be `http://localhost:4000/` instead.

**Comment by mmistakes** [comment]
Did you set `url` in your `_config.yml` to something or leave it blank? Leaving it blank causes links to the homepage not to work. They'll work in production just fine once you drop in your live domain or use `http://localhost:4000` when working locally.

This comes up all the time, see #64, #10, and #1 for more context.

**Comment by procedural** [comment]
Oh, yeah, you're right, I leaved it blank... Cool, thanks! Great theme, man!

**Comment by timedreamer** [comment]
Hi, I still got the same issue after I add the `url: "https://timedreamer.github.io"`. When I open [my website](https://timedreamer.github.io/), it automatically on page 2. And the `Previous` button goes to the same page. Here is [my repo](https://github.com/timedreamer/timedreamer.github.io).

Did I do anything wrong?

Thanks!
