### ISSUE TITLE
Code on a list has grey border and background

### ISSUE THREAD

**Issue by dyskette** [mmistakes/hpstr-jekyll-theme#86]
If there are code blocks inside a list, they have a grey border and background just like inline code, as you can see in the next screenshot.

![captura de pantalla de 2015-02-20 18 10 52](https://cloud.githubusercontent.com/assets/6687927/6311705/4a052e34-b92c-11e4-9789-f53db1a604e3.png)

Inside _typography.scss, lines [107-108](https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/_sass/_typography.scss#L107-L108) seems to be affecting both elements at the same time.

**Comment by mmistakes** [comment]
I don't know if there is anyway around that without bloating the CSS. Not to mention you don't typically see a large block of code that spans multiple lines placed in an item list, they're usually broken out as their own to be more readable.

It doesn't appear that you are including more than a single line of code in the example above. Why not just make it inline like the code snippet you have in the second list item below it?

**Comment by dyskette** [comment]
It's not the only post with block code inside a list, it can be a headache to change them all. In the meantime I workaround this by placing a ">" before "code" in line 101. I may be breaking something else though.

```
p,
li { 
	> code {
```

**Comment by mmistakes** [comment]
That looks like a good fix. I don't think it would break anything else.

**Comment by mmistakes** [comment]
Fixed in [1.7.6](https://github.com/mmistakes/hpstr-jekyll-theme/releases/tag/1.7.6)
