### ISSUE TITLE
Featured Image on list of posts

### ISSUE THREAD

**Issue by pathumego** [mmistakes/hpstr-jekyll-theme#87]
Hi.. is it possible to have a featured image for each post on the list of posts? Im looking for something that has this potion.. is it doable? if so just tell me how to.. and I will get it done :) Thanks

**Comment by mmistakes** [comment]
The theme already does this. If a post has a featured image assigned in it's YAML Front Matter then it will display in both the post list and single pages.

``` yaml
image:
  feature: example-image.jpg
```
