### ISSUE TITLE
Font Awesome Social Icons AdBlock Issue

### ISSUE THREAD

**Issue by rahul-rkt** [mmistakes/hpstr-jekyll-theme#98]
Some of the social icons used by Font Awesome like Twitter, Facebook, LinkedIn, etc. are blocked by AdBlocking extensions. The cause was traced to the use of Fanboy's Social Blocking List which blocks social icons. Threads have been opened but neither parties have come up with a fix. The solution is to rename the blocked social icons in your css so that it doesn't get picked up. I recommend you do add this fix for all the icons.

**Comment by mmistakes** [comment]
I'm not a big fan of messing with the Font Awesome class names just to get around an ad blocker that doesn't want to play nice. Looks like there may be a [fix with Font Awesome 5](https://github.com/FortAwesome/Font-Awesome/issues/1799), so I'll wait and see and update if/when that happens.

**Comment by rahul-rkt** [comment]
Yeah I saw the thread, it had been close previously. Hope they find a fix. At least document this issue in your theme setup page so that people know what to do. I am not good with frontend, and I had a stupidly tough time fixing this.

**Comment by mmistakes** [comment]
Don't use ad blocker plugins, problem solved ;-)
